source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'puma'
gem 'sqlite3'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'slim-rails'
gem 'bootstrap-sass'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails'
  gem 'rr'
  gem 'database_cleaner'
  gem 'activerecord-nulldb-adapter'
  gem 'fig_leaf'
end
